services:
  job-audio_prospector:
    build: ./service-audio_prospector
    volumes:
      - ./shared:/app/shared
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge