services:
  job-audio_prospector:
    build: ./service-audio_prospector
    volumes:
      - ./shared:/app/shared
      - ./test:/app/test
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5001:5001"
    networks:
      - app-network
  job-speech_recognizer:
    build: ./service-speech_recognizer
    volumes:
      - ./shared:/app/shared
      - ./test:/app/test
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5002:5002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge