services:
  api_gateway:
    build: ./service-job_supervisor
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge